added trivy for vulns and sboms added cosign to sign container image and attestations upgraded docker related actions

diff --git a/.github/workflows/release-operator.yml b/.github/workflows/release-operator.yml
--- a/.github/workflows/release-operator.yml
+++ b/.github/workflows/release-operator.yml
@@ -223,6 +223,9 @@ jobs:
       OPERATOR_IMAGE_REGISTRY: ${{ needs.setup.outputs.operator_image_registry }}
       BUNDLE_IMAGE_REPOSITORY: "${{ needs.setup.outputs.bundle_image_registry }}/${{ needs.setup.outputs.bundle_image_repository_name }}"
       BUNDLE_IMAGE_REGISTRY: ${{ needs.setup.outputs.bundle_image_registry }}
+    permissions:
+      contents: read
+      id-token: write
 
     steps:
       - name: Set up Go
@@ -232,6 +235,18 @@ jobs:
 
       - name: Check out code
         uses: actions/checkout@v4
+
+      - name: Validate variables
+        run: |          
+          if [ "${{ needs.setup.outputs.operator_image_registry }}" == "" ]; then
+            echo "Required setup outputs 'operator_image_registry' is not set. Check setup 'Complete Job' step."
+            exit 1
+          fi
+          
+          if [ "${{ needs.setup.outputs.bundle_image_registry }}" == "" ]; then
+            echo "Required setup outputs 'bundle_image_registry' is not set. Check setup 'Complete Job' step."
+            exit 1
+          fi
 
       - name: Go Build Cache
         uses: actions/cache@v3
@@ -280,14 +295,18 @@ jobs:
         run: make
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+        uses: docker/setup-qemu-action@v3
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
         with:
           buildkitd-flags: --debug
+
+      - name: Setup cosign
+        uses: sigstore/cosign-installer@v3
+
       - name: Login to Operator Registry
-        uses: docker/login-action@v1
+        uses: docker/login-action@v3
         with:
           registry: ${{ env.OPERATOR_IMAGE_REGISTRY }}
           username: ${{ secrets.REGISTRY_USERNAME }}
@@ -302,6 +321,49 @@ jobs:
           platforms: ${{ matrix.platform }}
           push: true
           tags: "${{ env.OPERATOR_IMAGE_REPOSITORY }}:latest-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }},${{ env.OPERATOR_IMAGE_REPOSITORY }}:${{ env.OPERATOR_VERSION }}-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }}"
+
+      - name: Cosign login and initialize
+        env:
+          image_registry: ${{ env.OPERATOR_IMAGE_REGISTRY }}
+        run: |
+          echo "${{ secrets.REGISTRY_PASSWORD }}" | cosign login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${image_registry%%/*}
+          cosign initialize
+
+      - name: Sign Operator Image
+        id: sign_operator
+        env:
+          IMAGE_URI: ${{ env.OPERATOR_IMAGE_REPOSITORY }}:latest-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }}
+        run: |
+          signed_image_digest=$(cosign triangulate --type=digest ${{ env.IMAGE_URI }})
+          echo "signed_image_digest=${signed_image_digest}" >> $GITHUB_OUTPUT
+          cosign sign --yes ${signed_image_digest}
+
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@0.14.0
+        env:
+          TRIVY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
+          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
+        with:
+          scan-type: image
+          image-ref: ${{ steps.sign_operator.outputs.signed_image_digest }}
+          format: "cosign-vuln"
+          output: "cosign-vuln.json"
+
+      - name: Run Trivy SBOM generator
+        uses: aquasecurity/trivy-action@0.14.0
+        env:
+          TRIVY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
+          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
+        with:
+          scan-type: image
+          image-ref: ${{ steps.sign_operator.outputs.signed_image_digest }}
+          format: "cyclonedx"
+          output: "cyclonedx-sbom.json"
+
+      - name: Attach attestations for Operator Image
+        run: |
+          cosign attest --yes --type vuln --predicate cosign-vuln.json ${{ steps.sign_operator.outputs.signed_image_digest }}
+          cosign attest --yes --type cyclonedx --predicate cyclonedx-sbom.json ${{ steps.sign_operator.outputs.signed_image_digest }}
 
       - name: Prepare Distribution Artifacts
         shell: bash
@@ -376,6 +438,10 @@ jobs:
       OPERATOR_IMAGE_REGISTRY: ${{ needs.setup.outputs.operator_image_registry }}
       BUNDLE_IMAGE_REPOSITORY: "${{ needs.setup.outputs.bundle_image_registry }}/${{ needs.setup.outputs.bundle_image_repository_name }}"
       BUNDLE_IMAGE_REGISTRY: ${{ needs.setup.outputs.bundle_image_registry }}
+    permissions:
+      contents: read
+      id-token: write
+      
     steps:
       - name: Set up Go
         uses: actions/setup-go@v4
@@ -435,13 +501,16 @@ jobs:
         run: operator-sdk bundle validate ./bundle --select-optional name=operatorhub
 
       - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+        uses: docker/setup-qemu-action@v3
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
+
+      - name: Setup cosign
+        uses: sigstore/cosign-installer@v3
 
       - name: Login to Bundle Registry
-        uses: docker/login-action@v1
+        uses: docker/login-action@v3
         with:
           registry: ${{ env.BUNDLE_IMAGE_REGISTRY }}
           username: ${{ secrets.REGISTRY_USERNAME }}
@@ -456,6 +525,50 @@ jobs:
           platforms: ${{ matrix.platform }}
           push: true
           tags: "${{ env.BUNDLE_IMAGE_REPOSITORY }}:latest-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }},${{ env.BUNDLE_IMAGE_REPOSITORY }}:${{ env.BUNDLE_VERSION }}-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }}"
+
+      - name: Cosign login and initialize
+        env:
+          image_registry: ${{ env.BUNDLE_IMAGE_REGISTRY }}
+        run: |
+          echo "${{ secrets.REGISTRY_PASSWORD }}" | cosign login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin ${image_registry%%/*}
+          cosign initialize
+
+      - name: Sign Bundle Image
+        id: sign_bundle
+        env:
+          IMAGE_URI: ${{ env.BUNDLE_IMAGE_REPOSITORY }}:latest-${{ steps.setup-build-step.outputs.platform_os }}-${{ steps.setup-build-step.outputs.platform_arch }}
+        run: |
+          signed_image_digest=$(cosign triangulate --type=digest ${{ env.IMAGE_URI }})
+          echo "signed_image_digest=${signed_image_digest}" >> $GITHUB_OUTPUT
+          cosign sign --yes ${signed_image_digest}
+
+      - name: Run Trivy vulnerability scanner
+        uses: aquasecurity/trivy-action@0.14.0
+        env:
+          TRIVY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
+          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
+        with:
+          scan-type: image
+          image-ref: ${{ steps.sign_bundle.outputs.signed_image_digest }}
+          format: "cosign-vuln"
+          output: "cosign-vuln.json"
+
+
+      - name: Run Trivy SBOM generator
+        uses: aquasecurity/trivy-action@0.14.0
+        env:
+          TRIVY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
+          TRIVY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
+        with:
+          scan-type: image
+          image-ref: ${{ steps.sign_bundle.outputs.signed_image_digest }}
+          format: "cyclonedx"
+          output: "cyclonedx-sbom.json"
+
+      - name: Attach attestations for Bundle Image
+        run: |
+          cosign attest --yes --type vuln --predicate cosign-vuln.json ${{ steps.sign_bundle.outputs.signed_image_digest }}
+          cosign attest --yes --type cyclonedx --predicate cyclonedx-sbom.json ${{ steps.sign_bundle.outputs.signed_image_digest }}
 
       - name: Prepare Distribution Artifacts
         shell: bash
